name: yakihonne
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.4+78

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  aescryptojs: ^1.0.0
  amberflutter:
    git:
      url: https://github.com/Seddik-Boukhalfa/amberflutter.git
      ref: master
  android_intent_plus: ^4.0.2
  animate_do: ^3.0.2
  app_links: ^3.5.0
  awesome_notifications: any
  bip340: ^0.2.0
  bolt11_decoder: ^1.0.2
  bot_toast: ^4.1.3
  buttons_tabbar: ^1.3.8
  cached_network_image: ^3.2.3
  calendar_date_picker2: ^0.5.3
  carousel_slider: ^4.2.1
  chat_gpt_sdk: ^2.2.8
  cloud_firestore: ^4.14.0
  connectivity_plus: ^5.0.2
  cryptography: ^2.7.0
  cupertino_icons: ^1.0.2
  device_info_plus: ^9.0.2
  dio: ^5.2.1+1
  dio_cookie_manager: ^3.1.0+1
  drift: ^2.15.0
  dropdown_button2: ^2.3.9
  easy_image_viewer: ^1.2.1
  equatable: ^2.0.5
  expandable: ^5.0.1
  extended_image: ^8.2.0
  firebase_analytics: ^10.5.1
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  fl_chart: ^0.68.0
  flex_color_picker: ^3.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^5.1.0
  flutter_easyloading: ^3.0.5
  flutter_hooks: ^0.19.0
  flutter_inappwebview: ^6.0.0
  flutter_link_previewer: ^3.2.2
  flutter_math_fork: ^0.7.1
  flutter_portal: ^0.4.0
  flutter_reaction_button: ^3.0.0+3
  flutter_reorderable_grid_view: ^4.0.0
  flutter_scroll_shadow: ^1.2.3
  flutter_secure_storage: ^9.0.0
  flutter_speed_dial: ^7.0.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_sticky_header: ^0.6.5
  flutter_svg: ^2.0.7
  form_field_validator: ^1.1.0
  giphy_api_client:
    git:
      url: https://github.com/Seddik-Boukhalfa/giphy_client.git
      ref: master
  html: ^0.15.4
  image_picker: ^1.0.0
  intl: 0.19.0
  just_audio: ^0.9.39
  kepler: ^1.0.3
  logger: ^2.4.0
  lottie: ^3.1.2
  markdown_widget: 2.3.1
  nested_scroll_view_plus: ^1.0.0
  numeral: ^2.0.1
  path: ^1.8.3
  path_drawing: ^1.0.1
  path_provider: ^2.1.2
  permission_handler: ^10.4.1
  pod_player: ^0.2.1
  pretty_qr_code: ^3.0.0
  pull_down_button: ^0.9.3
  pull_to_refresh: ^2.0.0
  qr_code_scanner:
    git:
      url: https://github.com/Seddik-Boukhalfa/qr_code_scanner.git
      ref: master
  responsive_framework: ^1.1.0
  screenshot: ^2.1.0
  selectable: ^0.3.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.0
  sizer: ^2.0.15
  skeletonizer: ^0.8.0
  sqlite3_flutter_libs: ^0.5.19+1
  string_validator: ^1.0.2
  top_snackbar_flutter: ^3.1.0
  url_launcher: ^6.1.14
  uuid: ^4.3.3
  video_url_validator: ^1.0.3

flutter_launcher_icons:
  android: true
  # ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/background.png"
  adaptive_icon_foreground: "assets/foreground.png"

dev_dependencies:
  build_runner: ^2.4.8
  drift_dev: ^2.15.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/features/
    - assets/icons/logos/
    - assets/icons/toasts/
    - assets/images/
    - assets/lottie/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
